import csv
import pandas as pd 
import matplotlib.pyplot as plt 
import math 
'''
I/O Utility functions. 
'''

def save_results_to_csv(simulator, filepath: str) -> None:
    fieldnames = ['time_s', 'biomass_total'] + list(simulator.concentrations_index_dict.keys())

    with open(filepath, mode='w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(fieldnames)

        # print(len(simulator.biomass_time_series))
        # print(simulator.concentrations_time_series)
        for t, biomass in enumerate(simulator.biomass_time_series):
            time_s = t * simulator.dt
            row = [time_s, biomass]

            for met in simulator.concentrations_index_dict.keys():
                total_conc = simulator.concentrations_time_series[met][t]
                row.append(total_conc)

            writer.writerow(row)

    print(f"Results saved to {filepath}")



def plot_results_to_pdf_grid(filepath: str, pdf_path: str = "results_grid.pdf",
                             col_width=4, row_height=3) -> None:
    """
    Load a CSV generated by save_results_to_csv() and create a PDF of subplots
    for biomass and each metabolite vs time, arranged in 3 columns. The figure
    size automatically adapts to the number of subplots.

    Parameters:
        filepath (str): Path to the CSV file.
        pdf_path (str): Output PDF filename.
        col_width (int): Width (in inches) of each subplot column.
        row_height (int): Height (in inches) of each subplot row.
    """
    # Load the data
    df = pd.read_csv(filepath)
    time = df['time_s'] / 3600.0  # Convert to hours
    components = [col for col in df.columns if col != 'time_s']  # biomass + metabolites

    # Grid setup
    n_plots = len(components)
    ncols = 3  # Always 3 columns
    nrows = math.ceil(n_plots / ncols)

    # Define figure size based on rows and columns
    fig_width = ncols * col_width
    fig_height = nrows * row_height
    fig, axes = plt.subplots(nrows=nrows, ncols=ncols,
                             figsize=(fig_width, fig_height))
    axes = axes.flatten()

    # Plot each component
    for idx, comp in enumerate(components):
        axes[idx].plot(time, df[comp], label=comp, linewidth=2)
        axes[idx].set_title(comp)
        axes[idx].set_xlabel('Time (hr)')
        axes[idx].set_ylabel('Total Amount (mmol)' if comp != 'biomass_total' else 'Biomass (gDW)')
        axes[idx].grid(True)

    # Turn off unused subplots if any
    for ax in axes[n_plots:]:
        ax.axis('off')

    plt.tight_layout()
    plt.savefig(pdf_path, format='pdf')
    plt.close()
    print(f"Plot saved to {pdf_path}")